function a_star_plot(map, costs, route)
% A_STAR_PLOT plots the output of A_STAR.
%   MAP is the MAP input to A_STAR
%   COSTS is the COST input to A_STAR
%   ROUTE is the output of A_STAR

% Alex Ranaldi
% alexranaldi@gmail.com

if ~islogical(map)
    error('map must be logical')
end

mapSize = size(map);

hf = figure( ...
    'Color', 'white' ...
);
ha = axes( ...
    'parent', hf, ...
    'ydir','reverse',...
    'xdir','normal',...
    'xlim', [1 mapSize(1)+1], ...
    'ylim', [1 mapSize(2)+1], ...
    'xtick', 1:mapSize(1)+1, ...
    'ytick', 1:mapSize(2)+1 ...
);

grid on;

% normalize costs
minCost = min(costs(:));
maxCost = max(costs(:));
mmCost = maxCost - minCost;
if mmCost == 0
    mmCost = 1;
end
costs = (costs(:) - minCost) / mmCost;
colorIndex = fix(costs*100)+1;
colors = jet(101);

for k = 1 : numel(map)
    [r, c] = ind2sub(mapSize, k);
    if map(k)
        patch( ...
            'parent', ha, ...
            'xdata', [c c c+1 c+1], ...
            'ydata', [r r+1 r+1 r], ...
            'facecolor', colors(colorIndex(k),:) ...
            );
    end
end

[r, c] = ind2sub(mapSize, route);

for k = 1 : length(route)
    line('parent', ha, ...
        'xdata', c + 0.5, ...
        'ydata', r + 0.5, ...
        'linewidth', 2, ...
        'color', 'r', ...
        'linestyle', '-.' ...
        );
end
